name: TagCreation

on:
    push:
        tags:
        - 'v*'
    workflow_dispatch:

permissions:
  contents: read

jobs:
  print_context:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Deploy
        shell: pwsh
        run: | 
          $ref = "${{github.event.ref}}"
          $tag = $ref.Split('/')[2]
          ./publish.ps1 -VersionTag $tag -NugetApiKey "${{secrets.NUGETAPIKEY}}" -Whatif

     