name: TagCreation

on:
    push:
        tags:
        - 'v*'
    workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - name: Tag name display
        run: |
          echo Tag Name is : ${{github.event.ref}}

        