name: TagCreation

on:
    push:
        tags:
        - 'v*'
    workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        shell: pwsh
        run: | 
          $ref = "${{github.event.ref}}"
          ./deploy.ps1 -ref $ref -verbose

      - name: Check commig
        shell: pwsh
        run: | 
          $VerbosePreference = 'Continue'

          $gitShow = git show -s
          $gitshow  | Write-Host
          
          $commit = $gitshow[0].Substring(7) 

          $tagref= "${{github.event.head_commit.id}}"

          "Actual commit [{0}] " -f $commit | Write-Host
          "ref    commit [{0}] " -f $tagref | write-host
          $equal = ($commit -eq $tagref)
          
          "Confirmed head commit [{0}]" -f $equal | Write-Host

      - name: Update Module Version
        shell: pwsh
        run: |

          $VerbosePreference = 'Continue'

          $ref = "${{github.event.ref}}"
       
          $tag = $ref.Split('/')[2]

          "Tag value [$tag]" | Write-Verbose

          $version = $tag.split('-')[0]

          "Version value [$version]" | Write-Verbose

          $preRelease = $tag.split('-')[1]

          "PreRelease value [$preRelease]" | Write-Verbose

          $manifestPath = Get-ChildItem -Path $PSScriptRoot -Filter *.psd1
          $parameters = @{
              ModuleVersion = $version
              Path = $manifestPath.FullName
              Prerelease = $preRelease
          }
          Update-ModuleManifest  @parameters   

          $manifestModified = Import-powerShellDataFile -Path $manifestPath.FullName

          $manifestModified
          $manifestModified.PrivateData.PSData

      






      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

        